
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const ON_MESSAGE_RESET = 'ON_MESSAGE_RESET';
export const ON_MESSAGE_CHANGE = 'ON_MESSAGE_CHANGE';
