
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const ON_MESSAGE_RESET = 'ON_MESSAGE_RESET';
export const ON_MESSAGE_CHANGE = 'ON_MESSAGE_CHANGE';

export const VALIDATE_TOKEN_START = 'VALIDATE_TOKEN_START';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAIL = 'VALIDATE_TOKEN_FAIL';
export const SAVE_AUTH_TOKEN = 'SAVE_AUTH_TOKEN';
export const SAVE_PHONE = 'SAVE_PHONE';
