export const FETCH_TOTAL_CONFIRMED_STARTED = 'FETCH_TOTAL_CONFIRMED_STARTED';
export const FETCH_TOTAL_DEATHS_STARTED = 'FETCH_TOTAL_DEATHS_STARTED';
export const FETCH_TOTAL_RECOVERED_STARTED = 'FETCH_TOTAL_RECOVERED_STARTED';
export const FETCH_DAILY_REPORTS_STARTED = 'FETCH_DAILY_REPORTS_STARTED';

export const FETCH_TOTAL_CONFIRMED_SUCCESS = 'FETCH_TOTAL_CONFIRMED_SUCCESS';
export const FETCH_TOTAL_DEATHS_SUCCESS = 'FETCH_TOTAL_DEATHS_SUCCESS';
export const FETCH_TOTAL_RECOVERED_SUCCESS = 'FETCH_TOTAL_RECOVERED_SUCCESS';
export const FETCH_DAILY_REPORTS_SUCCESS = 'FETCH_DAILY_REPORTS_SUCCESS';

export const FETCH_TOTAL_CONFIRMED_FAILURE = 'FETCH_TOTAL_CONFIRMED_FAILURE';
export const FETCH_TOTAL_DEATHS_FAILURE = 'FETCH_TOTAL_DEATHS_FAILURE';
export const FETCH_TOTAL_RECOVERED_FAILURE = 'FETCH_TOTAL_RECOVERED_FAILURE';
export const FETCH_DAILY_REPORTS_FAILURE = 'FETCH_DAILY_REPORTS_FAILURE';

export const RESET = 'RESET';
