export default {
  translation: {
    'Welcome to React': 'Welcome to React and react-i18next',
    Outbox: 'Outbox',
    Drafts: 'Drafts',
    Text: 'Text',
    'Text + buttons': 'Text + buttons',
    'Image + buttons': 'Image + buttons',
    'Style 1': 'Style 1',
    'Style 2': 'Style 2',
    'Style 3': 'Style 3',
    app_title: 'COVID-19 Broadcasting System of The Kingdom of Cambodia',
    logout_title: 'logout from system?',
    cancel: 'Cancel',
    reset: 'Reset',
    send: 'Send',
    ok: 'OK',
    'Something went wrong': 'Something went wrong!',
    'Are you sure you want to send': 'Are you sure you want to send this message?',
    'send message': 'Send message to {{provider}}',
    invalid_phone: 'Invalid phone number! Please check your phone number',
    login_with_phone: 'Login with your phone number',
    enter_otp: 'Enter your OTP you recieve from SMS',
    phone_placeholder: 'e.g +855123456789',
    otp_placeholder: '6 digits code',
    send_code: 'Send Codes',
    login: 'Login',
    text_message: 'Text Message',
    not_recieve_code: "Didn't recieve your OTP code?",
    resend_otp: 'Resend OTP',
    change_phone: 'Re-enter your phone number',
  },
};
