export default {
  translation: {
    'Welcome to React': 'សូមស្វាគមន៍មកកាន់ React',
    Outbox: 'ប្រអប់​ចេញ',
    Drafts: 'សំណេរព្រៀង',
    Text: 'អត្ថបទ',
    'Text + buttons': 'អត្ថបទ + ប៊ូតុង',
    'Image + buttons': 'រូបភាព + ប៊ូតុង',
    'Style 1': 'លំនាំ​ ទី១',
    'Style 2': 'លំនាំ ទី២',
    'Style 3': 'លំនាំ ទី៣',
    app_title: 'ប្រព័ន្ធផ្សព្វផ្សាយ COVID-19 នៃ​ព្រះ​រាជាណាចក្រ​កម្ពុជា',
    logout_title: 'ចាកចេញពី ប្រព័ន្ធផ្សព្វផ្សាយ COVID-19?',
    cancel: 'បោះបង់',
    reset: 'លុបចោល',
    send: 'ផ្ញើ',
    ok: 'បាទ/ចាស',
    'Something went wrong': 'ប្រព័ន្ធផ្សព្វផ្សាយ',
    'Are you sure you want to send': 'ប្រព័ន្ធផ្សព្វផ្សាយ',
    'send message': 'ផ្ញើសារទៅកាន់​ {{provider}}',
    invalid_phone: 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ! សូមពិនិត្យម្ដងទៀត...',
    login_with_phone: 'ចូលប្រើដោយលេខទូរស័ព្ទ',
    enter_otp: 'បញ្ជូលលេខសម្ងាត់',
    phone_placeholder: 'ឧ +៨៥៥១២៣៤៥៦៧៨៩',
    otp_placeholder: 'លេខសម្ងាត់៦ខ្ទង់',
    send_code: 'ផ្ញើលេខសម្ងាត់',
    login: 'ចូលប្រើ',
    text_message: 'សារ',
    not_recieve_code: 'មិនទទួលបានលេខសម្ងាត់​របស់អ្នក?',
    resend_otp: 'ផ្ញើម្ដងទៀត',
    change_phone: 'បញ្ជូលលេខទូរស័ព្ទម្តងទៀត',
  },
};
